# Generated by Django 2.1.3 on 2018-12-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='aluno',
        ),
        migrations.AddField(
            model_name='aula',
            name='aluno',
            field=models.ManyToManyField(related_name='Aluno', to='core.Usuario'),
        ),
    ]
